---
- name: Test raw module via ssh
  hosts: all
  gather_facts: false
  tasks:

    - name: Get system status # noqa 301
      raw: get system status
      register: res

    - debug:
        var: res.stdout_lines
