---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  # Required to communicat with libvirtd
  become: true
  tasks:

    - include_tasks: create_virsh_tasks.yml
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: platform
