---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  #no_log: "{{ molecule_no_log }}"
  become: true
  tasks:

    - include_tasks: destroy_virsh_tasks.yml
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: platform
