---
dependency:
  name: galaxy
driver:
  name: delegated
lint:
  name: yamllint
platforms:
  - name: fortios
    image_file: /home/onagano/tmp/fortios.qcow2
    admin_password: RedHat1!
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: debug
  inventory:
    group_vars:
      all:
        ansible_user: admin
        ansible_password: RedHat1!
        ansible_python_interpreter: ${MOLECULE_PROJECT_DIRECTORY}/.tox/py37/bin/python
verifier:
  name: ansible
  lint:
    name: ansible-lint
